import Foundation
import XCTest
@testable import My_Island

final class MeetingMemoPipelineTests: XCTestCase {
    func testUntitledMeetingGetsAutoGeneratedTopicFromSummaryAndDate() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "会议围绕美国住宅VPN方案、VPS采购与浏览器隔离策略展开讨论，重点比较成本、稳定性与后续落地路径。",
                            source: "memo-lark"
                        )
                    )
                },
                buildLocalSummary: { transcript, topic, _ in
                    MeetingSummaryBundle(fullSummary: "\(topic):\(transcript.count)", source: "agent-fallback")
                },
                buildPostMeetingAdvice: { _, _, _, _, _, _ in [] }
            )
        )
        let localURL = makeTempAudioFile()
        let record = MeetingRecord(
            id: "meeting-untitled",
            topic: "未命名会议",
            state: .processing,
            createdAt: fixedDate(year: 2026, month: 4, day: 11),
            transcript: [TranscriptSegment(text: "我们先比较美国住宅 VPN 方案。", startTimeMs: 0, endTimeMs: 1000)]
        )

        let processed = await engine.process(
            record: record,
            localAudioURL: localURL,
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )

        XCTAssertEqual(processed.topic, "美国住宅VPN方案 2026-04-11")
    }

    func testUserProvidedTopicIsPreservedAfterPostProcessing() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "会议围绕美国住宅VPN方案、VPS采购与浏览器隔离策略展开讨论，重点比较成本、稳定性与后续落地路径。",
                            source: "memo-lark"
                        )
                    )
                },
                buildLocalSummary: { transcript, topic, _ in
                    MeetingSummaryBundle(fullSummary: "\(topic):\(transcript.count)", source: "agent-fallback")
                },
                buildPostMeetingAdvice: { _, _, _, _, _, _ in [] }
            )
        )
        let localURL = makeTempAudioFile()
        let record = MeetingRecord(
            id: "meeting-named",
            topic: "VPN 商业计划",
            state: .processing,
            createdAt: fixedDate(year: 2026, month: 4, day: 11),
            transcript: [TranscriptSegment(text: "我们先比较美国住宅 VPN 方案。", startTimeMs: 0, endTimeMs: 1000)]
        )

        let processed = await engine.process(
            record: record,
            localAudioURL: localURL,
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )

        XCTAssertEqual(processed.topic, "VPN 商业计划")
    }

    func testMemoSuccessWritesBackIntoOriginalMeetingAndRetryReusesUploadedObject() async throws {
        let spy = MeetingPostProcessingSpy()
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    await spy.recordUpload(for: record.id)
                    return MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com/first")!
                    )
                },
                buildRemoteAudioURL: { objectKey, _ in
                    await spy.recordReuse(for: objectKey)
                    return URL(string: "https://download.example.com/retry")!
                },
                submitMemo: { url, _, _, _ in
                    await spy.recordSubmit(url: url)
                    return "task-1"
                },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(fullSummary: "豆包妙记总结", source: "memo-lark")
                    )
                },
                buildLocalSummary: { transcript, topic, _ in
                    MeetingSummaryBundle(fullSummary: "\(topic):\(transcript.count)", source: "agent-fallback")
                },
                buildPostMeetingAdvice: { _, _, _, _, selectedSkillIDs, _ in
                    [
                        MeetingAdviceCard(
                            title: "会后建议",
                            body: "核心判断：先收敛问题。被忽略的问题：场景成立性。下一步建议：明确 owner。",
                            triggerRuleID: "post_meeting_review",
                            skillIDs: selectedSkillIDs,
                            source: "post-agent",
                            coreJudgment: "先收敛问题。",
                            blindSpot: "场景成立性。",
                            nextStep: "明确 owner。"
                        )
                    ]
                }
            )
        )
        let localURL = makeTempAudioFile()
        let installedSkills = [makeSkill(id: "skill-1", name: "Skill 1")]
        let record = MeetingRecord(
            id: "meeting-1",
            topic: "产品评审",
            state: .processing,
            createdAt: Date(timeIntervalSince1970: 1_700_000_000),
            transcript: [TranscriptSegment(text: "先定义问题", startTimeMs: 0, endTimeMs: 1000)],
            selectedSkillIDs: ["skill-1"]
        )

        let first = await engine.process(
            record: record,
            localAudioURL: localURL,
            installedSkills: installedSkills,
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )
        let second = await engine.process(
            record: first,
            localAudioURL: localURL,
            installedSkills: installedSkills,
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )

        XCTAssertEqual(first.id, record.id)
        XCTAssertEqual(first.summaryBundle?.fullSummary, "豆包妙记总结")
        XCTAssertEqual(first.uploadedAudioObjectKey, "meetings/2026/meeting-1/master.wav")
        XCTAssertEqual(first.postMeetingAdviceCards.count, 1)
        let snapshot = await spy.snapshot()
        XCTAssertEqual(snapshot.uploadCount, 1)
        XCTAssertEqual(snapshot.reuseCount, 1)
        XCTAssertEqual(snapshot.submittedURLs, [
            "https://download.example.com/first",
            "https://download.example.com/retry"
        ])
        XCTAssertEqual(second.id, record.id)
        XCTAssertEqual(second.uploadedAudioObjectKey, first.uploadedAudioObjectKey)
    }

    func testMemoFailureFallsBackToLocalSummaryAndKeepsMeetingCompleted() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in throw NSError(domain: "memo", code: 1, userInfo: [NSLocalizedDescriptionKey: "timeout"]) },
                buildLocalSummary: { transcript, _, _ in
                    MeetingSummaryBundle(fullSummary: transcript.map(\.text).joined(separator: " "), source: "agent-fallback")
                },
                buildPostMeetingAdvice: { _, _, _, _, _, _ in [] }
            )
        )
        let localURL = makeTempAudioFile()
        let record = MeetingRecord(
            id: "meeting-2",
            topic: "商业计划",
            state: .processing,
            createdAt: Date(timeIntervalSince1970: 1_700_000_000),
            transcript: [TranscriptSegment(text: "先定义商业场景", startTimeMs: 0, endTimeMs: 1000)]
        )

        let processed = await engine.process(
            record: record,
            localAudioURL: localURL,
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )

        XCTAssertEqual(processed.state, .completed)
        XCTAssertEqual(processed.summaryBundle?.source, "agent-fallback")
        XCTAssertTrue(processed.notes.contains(where: { $0.contains("豆包妙记失败") }))
    }

    func testForceSummaryRefreshRebuildsSummaryFromTranscriptWhenMemoFails() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { _, _, _ in
                    throw NSError(domain: "memo", code: 2, userInfo: [NSLocalizedDescriptionKey: "missing audio"])
                },
                buildRemoteAudioURL: { _, _ in
                    XCTFail("Existing uploaded audio should not be reused when local audio is unavailable")
                    return URL(string: "https://download.example.com")!
                },
                submitMemo: { _, _, _, _ in
                    XCTFail("Memo submission should fail before submit when audio is unavailable")
                    return "task-1"
                },
                pollMemo: { _, _, _ in
                    XCTFail("Memo polling should not run when audio upload fails")
                    return MeetingMemoArtifact()
                },
                buildLocalSummary: { transcript, _, _ in
                    MeetingSummaryBundle(
                        fullSummary: transcript.map(\.text).joined(separator: " / "),
                        source: "agent-fallback"
                    )
                },
                buildPostMeetingAdvice: { _, _, summaryBundle, _, _, _ in
                    XCTAssertEqual(summaryBundle?.fullSummary, "重新总结第一句 / 重新总结第二句")
                    return []
                }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "meeting-force-refresh",
                topic: "未命名会议",
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                transcript: [
                    TranscriptSegment(text: "重新总结第一句", startTimeMs: 0, endTimeMs: 1_000),
                    TranscriptSegment(text: "重新总结第二句", startTimeMs: 1_000, endTimeMs: 2_000)
                ],
                summaryBundle: MeetingSummaryBundle(fullSummary: "旧总结", source: "memo-lark")
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent(),
            forceSummaryRefresh: true
        )

        XCTAssertEqual(processed.summaryBundle?.fullSummary, "重新总结第一句 / 重新总结第二句")
        XCTAssertEqual(processed.summaryBundle?.source, "agent-fallback")
    }

    func testForceTranscriptRefreshReplacesExistingTranscriptAndSpeakerSpansFromMemoArtifact() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(fullSummary: "离线刷新后的总结", source: "memo-lark"),
                        transcriptSegments: [
                            TranscriptSegment(
                                id: "memo-1",
                                text: "离线刷新后的第一句",
                                startTimeMs: 0,
                                endTimeMs: 900,
                                speakerLabel: "speaker_7",
                                isFinal: true,
                                source: "doubao-memo"
                            )
                        ],
                        speakerSpans: [
                            SpeakerSpan(
                                id: "memo-1",
                                speakerLabel: "speaker_7",
                                startTimeMs: 0,
                                endTimeMs: 900
                            )
                        ]
                    )
                },
                buildLocalSummary: { _, _, _ in
                    XCTFail("Memo 成功时不应回退到本地总结")
                    return MeetingSummaryBundle()
                },
                buildPostMeetingAdvice: { _, transcript, _, _, _, _ in
                    XCTAssertEqual(transcript.map(\.text), ["离线刷新后的第一句"])
                    return []
                }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "meeting-force-transcript",
                topic: "历史会议",
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                transcript: [
                    TranscriptSegment(
                        id: "live-1",
                        text: "旧 transcript",
                        startTimeMs: 0,
                        endTimeMs: 800,
                        speakerLabel: "speaker_1"
                    )
                ],
                speakerSpans: [
                    SpeakerSpan(
                        id: "live-1",
                        speakerLabel: "speaker_1",
                        startTimeMs: 0,
                        endTimeMs: 800
                    )
                ]
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent(),
            forceSummaryRefresh: true,
            forceTranscriptRefresh: true
        )

        XCTAssertEqual(processed.transcript.map(\.text), ["离线刷新后的第一句"])
        XCTAssertEqual(processed.speakerSpans.map(\.speakerLabel), ["speaker_7"])
        XCTAssertEqual(processed.summaryBundle?.fullSummary, "离线刷新后的总结")
    }

    func testWeakMemoSummaryFallsBackToStructuredAgentSummary() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "弱结果第一句 弱结果第二句",
                            source: "memo-lark"
                        ),
                        transcriptSegments: [
                            TranscriptSegment(
                                id: "memo-1",
                                text: "弱结果第一句",
                                startTimeMs: 0,
                                endTimeMs: 800,
                                speakerLabel: "speaker_1",
                                isFinal: true,
                                source: "doubao-memo"
                            ),
                            TranscriptSegment(
                                id: "memo-2",
                                text: "弱结果第二句",
                                startTimeMs: 900,
                                endTimeMs: 1_600,
                                speakerLabel: "speaker_2",
                                isFinal: true,
                                source: "doubao-memo"
                            )
                        ],
                        speakerSpans: [
                            SpeakerSpan(id: "memo-1", speakerLabel: "speaker_1", startTimeMs: 0, endTimeMs: 800),
                            SpeakerSpan(id: "memo-2", speakerLabel: "speaker_2", startTimeMs: 900, endTimeMs: 1_600)
                        ]
                    )
                },
                buildLocalSummary: { transcript, _, _ in
                    XCTAssertEqual(transcript.map(\.text), ["弱结果第一句", "弱结果第二句"])
                    return MeetingSummaryBundle(
                        fullSummary: "结构化总结",
                        chapterSummaries: [MeetingChapterSummary(title: "问题定义", summary: "先锁定问题边界。")],
                        actionItems: [MeetingActionItem(task: "补齐路线图", owner: "Alice", dueDate: nil)],
                        qaPairs: [MeetingQAPair(question: "为什么现在推进？", answer: "因为窗口期短。")],
                        processHighlights: ["先定义问题"],
                        source: "agent-fallback"
                    )
                },
                buildPostMeetingAdvice: { _, _, summaryBundle, _, _, _ in
                    XCTAssertEqual(summaryBundle?.chapterSummaries.first?.title, "问题定义")
                    return []
                }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "meeting-weak-memo",
                topic: "历史会议",
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12)
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent(),
            forceSummaryRefresh: true,
            forceTranscriptRefresh: true
        )

        XCTAssertEqual(processed.summaryBundle?.fullSummary, "结构化总结")
        XCTAssertEqual(processed.summaryBundle?.source, "memo-lark+agent-fallback")
        XCTAssertEqual(processed.summaryBundle?.chapterSummaries.first?.title, "问题定义")
        XCTAssertEqual(processed.summaryBundle?.actionItems.first?.task, "补齐路线图")
        XCTAssertTrue(processed.notes.contains(where: { $0.contains("弱总结") || $0.contains("结构化总结") }))
    }

    func testStructuredMemoSummaryIsPreservedWithoutFallback() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "真正的妙记总结",
                            chapterSummaries: [MeetingChapterSummary(title: "背景", summary: "重新定义问题。")],
                            actionItems: [MeetingActionItem(task: "确认 owner", owner: nil, dueDate: nil)],
                            qaPairs: [MeetingQAPair(question: "为什么现在做？", answer: "窗口期短。")],
                            processHighlights: ["先定义问题"],
                            source: "memo-lark"
                        )
                    )
                },
                buildLocalSummary: { _, _, _ in
                    XCTFail("结构化 memo 结果存在时不应回退到 agent 总结")
                    return MeetingSummaryBundle()
                },
                buildPostMeetingAdvice: { _, _, summaryBundle, _, _, _ in
                    XCTAssertEqual(summaryBundle?.fullSummary, "真正的妙记总结")
                    return []
                }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "meeting-strong-memo",
                topic: "历史会议",
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                transcript: [TranscriptSegment(text: "旧内容", startTimeMs: 0, endTimeMs: 800)]
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent(),
            forceSummaryRefresh: true
        )

        XCTAssertEqual(processed.summaryBundle?.source, "memo-lark")
        XCTAssertEqual(processed.summaryBundle?.chapterSummaries.first?.title, "背景")
        XCTAssertEqual(processed.summaryBundle?.qaPairs.first?.answer, "窗口期短。")
    }

    func testObjectStorageUploadStillOccursWhenMemoIsDisabled() async throws {
        let spy = MeetingPostProcessingSpy()
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    await spy.recordUpload(for: record.id)
                    return MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com/audio")!
                    )
                },
                buildRemoteAudioURL: { _, _ in
                    XCTFail("不应在首次上传时复用远端对象")
                    return URL(string: "https://download.example.com/audio")!
                },
                submitMemo: { _, _, _, _ in
                    XCTFail("未配置妙记时不应提交妙记任务")
                    return "task-1"
                },
                pollMemo: { _, _, _ in
                    XCTFail("未配置妙记时不应轮询妙记任务")
                    return MeetingMemoArtifact()
                },
                buildLocalSummary: { transcript, _, _ in
                    MeetingSummaryBundle(
                        fullSummary: transcript.map(\.text).joined(separator: " "),
                        source: "agent-fallback"
                    )
                },
                buildPostMeetingAdvice: { _, _, _, _, _, _ in [] }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "meeting-remote-backup-only",
                topic: "远端备份测试",
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                transcript: [
                    TranscriptSegment(text: "本地录音需要同时保留远端备份。", startTimeMs: 0, endTimeMs: 900)
                ]
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: DoubaoMemoConfig(
                submitURL: "",
                queryURL: "",
                appID: "",
                accessToken: "",
                resourceID: ""
            ),
            agentConfig: configuredAgent()
        )

        let snapshot = await spy.snapshot()
        XCTAssertEqual(snapshot.uploadCount, 1)
        XCTAssertEqual(processed.uploadedAudioObjectKey, "meetings/2026/meeting-remote-backup-only/master.wav")
        XCTAssertEqual(processed.uploadedAudioRemoteURL, "https://download.example.com/audio")
        XCTAssertEqual(processed.summaryBundle?.source, "agent-fallback")
        XCTAssertEqual(processed.state, .completed)
    }

    func testMemoCanReuseExistingUploadedAudioWhenLocalAudioIsMissing() async throws {
        let spy = MeetingPostProcessingSpy()
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { _, _, _ in
                    XCTFail("已有远端对象时不应重新上传")
                    return MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/reused/master.wav",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com/reused")!
                    )
                },
                buildRemoteAudioURL: { objectKey, _ in
                    await spy.recordReuse(for: objectKey)
                    return URL(string: "https://download.example.com/reused")!
                },
                submitMemo: { url, _, _, _ in
                    await spy.recordSubmit(url: url)
                    return "task-1"
                },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "复用远端音频完成总结。",
                            source: "memo-lark"
                        ),
                        transcriptSegments: [
                            TranscriptSegment(
                                id: "memo-1",
                                text: "远端音频也可以重跑转写。",
                                startTimeMs: 0,
                                endTimeMs: 1_000,
                                speakerLabel: "speaker_2",
                                isFinal: true,
                                source: "doubao-memo"
                            )
                        ],
                        speakerSpans: [
                            SpeakerSpan(
                                id: "memo-1",
                                speakerLabel: "speaker_2",
                                startTimeMs: 0,
                                endTimeMs: 1_000
                            )
                        ]
                    )
                },
                buildLocalSummary: { _, _, _ in
                    XCTFail("复用远端音频成功时不应回退到本地总结")
                    return MeetingSummaryBundle()
                },
                buildPostMeetingAdvice: { _, transcript, _, _, _, _ in
                    XCTAssertEqual(transcript.map(\.text), ["远端音频也可以重跑转写。"])
                    return []
                }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "meeting-reuse-remote-audio",
                topic: "远端重跑",
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                uploadedAudioObjectKey: "meetings/2026/reused/master.wav"
            ),
            localAudioURL: nil,
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent(),
            forceSummaryRefresh: true,
            forceTranscriptRefresh: true
        )

        let snapshot = await spy.snapshot()
        XCTAssertEqual(snapshot.reuseCount, 1)
        XCTAssertEqual(snapshot.submittedURLs, ["https://download.example.com/reused"])
        XCTAssertEqual(processed.uploadedAudioRemoteURL, "https://download.example.com/reused")
        XCTAssertEqual(processed.summaryBundle?.fullSummary, "复用远端音频完成总结。")
        XCTAssertEqual(processed.transcript.map(\.text), ["远端音频也可以重跑转写。"])
    }

    func testImportedMediaMeetingBackfillsTranscriptFromMemoArtifact() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.m4a",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "会议先定义问题，再讨论执行顺序。",
                            source: "memo-lark"
                        ),
                        transcriptSegments: [
                            TranscriptSegment(
                                id: "memo-1",
                                text: "先定义问题。",
                                startTimeMs: 0,
                                endTimeMs: 900,
                                speakerLabel: "speaker_1",
                                isFinal: true,
                                source: "doubao-memo"
                            ),
                            TranscriptSegment(
                                id: "memo-2",
                                text: "再讨论执行顺序。",
                                startTimeMs: 1_000,
                                endTimeMs: 2_000,
                                speakerLabel: "speaker_2",
                                isFinal: true,
                                source: "doubao-memo"
                            )
                        ],
                        speakerSpans: [
                            SpeakerSpan(
                                id: "memo-1",
                                speakerLabel: "speaker_1",
                                startTimeMs: 0,
                                endTimeMs: 900
                            ),
                            SpeakerSpan(
                                id: "memo-2",
                                speakerLabel: "speaker_2",
                                startTimeMs: 1_000,
                                endTimeMs: 2_000
                            )
                        ]
                    )
                },
                buildLocalSummary: { _, _, _ in
                    XCTFail("Imported media with memo transcript should not need local summary fallback")
                    return MeetingSummaryBundle()
                },
                buildPostMeetingAdvice: { _, transcript, _, _, _, _ in
                    XCTAssertEqual(transcript.map(\.text), ["先定义问题。", "再讨论执行顺序。"])
                    return []
                }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "imported-media",
                topic: "导入会议",
                isTopicUserProvided: false,
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                sourceMediaRelativePath: "imported/source.mov",
                sourceMediaKind: .video,
                sourceMediaDisplayName: "source.mov"
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )

        XCTAssertEqual(processed.state, .completed)
        XCTAssertEqual(processed.transcript.map(\.source), ["doubao-memo", "doubao-memo"])
        XCTAssertEqual(processed.speakerSpans.map(\.speakerLabel), ["speaker_1", "speaker_2"])
        XCTAssertEqual(processed.summaryBundle?.fullSummary, "会议先定义问题，再讨论执行顺序。")
    }

    func testImportedMediaMeetingFailsWhenMemoProducesNoTranscript() async throws {
        let engine = MeetingPostProcessingEngine(
            dependencies: .init(
                ensureRemoteAudio: { record, _, _ in
                    MeetingUploadedAudioAsset(
                        objectKey: "meetings/2026/\(record.id)/master.m4a",
                        uploadURL: URL(string: "https://upload.example.com")!,
                        downloadURL: URL(string: "https://download.example.com")!
                    )
                },
                buildRemoteAudioURL: { _, _ in URL(string: "https://download.example.com")! },
                submitMemo: { _, _, _, _ in "task-1" },
                pollMemo: { _, _, _ in
                    MeetingMemoArtifact(
                        summaryBundle: MeetingSummaryBundle(
                            fullSummary: "只有摘要，没有逐句转写。",
                            source: "memo-lark"
                        )
                    )
                },
                buildLocalSummary: { _, _, _ in
                    XCTFail("Imported media without transcript should fail instead of fabricating a fallback summary")
                    return MeetingSummaryBundle()
                },
                buildPostMeetingAdvice: { _, _, _, _, _, _ in [] }
            )
        )

        let processed = await engine.process(
            record: MeetingRecord(
                id: "imported-media-no-transcript",
                topic: "导入失败",
                isTopicUserProvided: false,
                state: .processing,
                createdAt: fixedDate(year: 2026, month: 4, day: 12),
                sourceMediaRelativePath: "imported/source.mp3",
                sourceMediaKind: .audio,
                sourceMediaDisplayName: "source.mp3"
            ),
            localAudioURL: makeTempAudioFile(),
            installedSkills: [],
            objectStorageConfig: MeetingObjectStorageConfig(stsURL: "https://sts.example.com", stsBearerToken: ""),
            memoConfig: configuredMemo(),
            agentConfig: configuredAgent()
        )

        XCTAssertEqual(processed.state, .failed)
        XCTAssertTrue(processed.transcript.isEmpty)
        XCTAssertTrue(processed.lastError?.contains("离线转录不可用") == true)
        XCTAssertTrue(processed.notes.contains(where: { $0.contains("离线转录不可用") }))
    }

    private func configuredMemo() -> DoubaoMemoConfig {
        DoubaoMemoConfig(
            submitURL: "https://memo.example.com/submit",
            queryURL: "https://memo.example.com/query",
            appID: "app",
            accessToken: "token",
            resourceID: "volc.lark.minutes"
        )
    }

    private func configuredAgent() -> MeetingAgentModelConfig {
        MeetingAgentModelConfig(
            baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
            apiKey: "token",
            model: "qwen-plus",
            temperature: 0.2,
            systemPrompt: "你是会议助手"
        )
    }

    private func makeSkill(id: String, name: String) -> MeetingSkillInstall {
        MeetingSkillInstall(
            id: id,
            catalogEntryID: id,
            displayName: name,
            repoURL: "https://github.com/\(id)",
            repoFullName: id,
            installedAt: .distantPast,
            skillRelativePath: "Skills/\(id)/SKILL.md",
            readmeRelativePath: nil,
            localSnapshotDirectory: "Skills/\(id)",
            defaultBranch: "main",
            sourceIndexURL: "https://example.com/index",
            description: name,
            skillMarkdown: "# SKILL\n\(name)"
        )
    }

    private func makeTempAudioFile() -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString + ".wav")
        try? Data(repeating: 0x11, count: 1024).write(to: url)
        addTeardownBlock {
            try? FileManager.default.removeItem(at: url)
        }
        return url
    }

    private func fixedDate(year: Int, month: Int, day: Int) -> Date {
        var components = DateComponents()
        components.calendar = Calendar(identifier: .gregorian)
        components.timeZone = TimeZone(secondsFromGMT: 0)
        components.year = year
        components.month = month
        components.day = day
        components.hour = 9
        return components.date ?? Date(timeIntervalSince1970: 0)
    }
}

private actor MeetingPostProcessingSpy {
    private(set) var uploadCount = 0
    private(set) var reuseCount = 0
    private(set) var submittedURLs: [String] = []

    func recordUpload(for _: String) {
        uploadCount += 1
    }

    func recordReuse(for _: String) {
        reuseCount += 1
    }

    func recordSubmit(url: URL) {
        submittedURLs.append(url.absoluteString)
    }

    func snapshot() -> (uploadCount: Int, reuseCount: Int, submittedURLs: [String]) {
        (uploadCount, reuseCount, submittedURLs)
    }
}
