//
//  ClipboardPrivacyFilter.swift
//  MyIsland
//
//  Basic filtering to avoid capturing transient or synthetic pasteboard content.
//

import AppKit

enum ClipboardPrivacyFilter {
    nonisolated private static let ignoredMarkerTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-remote-clipboard",
    ]

    nonisolated static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        let typeIdentifiers = Set(allTypes(in: pasteboard))
        return !ignoredMarkerTypes.isDisjoint(with: typeIdentifiers)
    }

    nonisolated private static func allTypes(in pasteboard: NSPasteboard) -> [String] {
        var results = pasteboard.types?.map(\.rawValue) ?? []

        if let items = pasteboard.pasteboardItems {
            for item in items {
                results.append(contentsOf: item.types.map(\.rawValue))
            }
        }

        return results
    }
}
